name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: myenvironment
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: checking secret token
        run: echo ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checking secret username
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}
      - name: checking env token
        run: echo ${{ env.DOCKERHUB_TOKEN }}
       
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ serets.DOCKERHUB_TOKEN }}
          # password: dckr_pat_3klrNVI3YNWQUofwGcTw3lBa2Qo
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sujith071/testrepo:latest
          
